# Form implementation generated from reading ui file 'e:\bat\functions\Python\PyQtProject\DragonGateSpider\libs\gui\DragonGateSpider.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DragonGateSpider(object):
    def setupUi(self, DragonGateSpider):
        DragonGateSpider.setObjectName("DragonGateSpider")
        DragonGateSpider.resize(580, 414)
        DragonGateSpider.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=DragonGateSpider)
        self.centralwidget.setObjectName("centralwidget")
        self.logger = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.logger.setGeometry(QtCore.QRect(10, 10, 471, 341))
        self.logger.setStyleSheet("background: rgb(0, 0, 0)")
        self.logger.setReadOnly(True)
        self.logger.setObjectName("logger")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(490, 130, 75, 71))
        self.login_button.setStyleSheet("background-color: rgb(0, 255, 0)")
        self.login_button.setObjectName("login_button")
        DragonGateSpider.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=DragonGateSpider)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 25))
        self.menubar.setObjectName("menubar")
        self.functions_menu = QtWidgets.QMenu(parent=self.menubar)
        self.functions_menu.setObjectName("functions_menu")
        self.plugins_menu = QtWidgets.QMenu(parent=self.menubar)
        self.plugins_menu.setObjectName("plugins_menu")
        self.disabled_plugins_menu = QtWidgets.QMenu(parent=self.menubar)
        self.disabled_plugins_menu.setObjectName("disabled_plugins_menu")
        DragonGateSpider.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=DragonGateSpider)
        self.statusbar.setObjectName("statusbar")
        DragonGateSpider.setStatusBar(self.statusbar)
        self.menubar.addAction(self.functions_menu.menuAction())
        self.menubar.addAction(self.plugins_menu.menuAction())
        self.menubar.addAction(self.disabled_plugins_menu.menuAction())

        self.retranslateUi(DragonGateSpider)
        QtCore.QMetaObject.connectSlotsByName(DragonGateSpider)

    def retranslateUi(self, DragonGateSpider):
        _translate = QtCore.QCoreApplication.translate
        DragonGateSpider.setWindowTitle(_translate("DragonGateSpider", "MainWindow"))
        self.login_button.setText(_translate("DragonGateSpider", "登录"))
        self.functions_menu.setTitle(_translate("DragonGateSpider", "功能"))
        self.plugins_menu.setTitle(_translate("DragonGateSpider", "插件"))
        self.disabled_plugins_menu.setTitle(_translate("DragonGateSpider", "禁用的插件"))
